Repository swoosh/swoosh, pull requests merged in 2020-10, with the labels that each got.

#441 use GitHub CI
  .github/workflows/elixir.yml
  .travis.yml
Labels: skip-changelog

#527 Update release-drafter.yml
  .github/release-drafter.yml
Labels: skip-changelog

#528 v1.0.5
  CHANGELOG.md
  lib/swoosh.ex
  mix.exs
Labels: skip-changelog

#529 Misc fixes and changes to HTML doc generation
  README.md
  mix.exs
Labels: docs

#532 Mailjet: short circuit deliver_many to prevent error when delivering 0 emails
  lib/swoosh/adapters/mailjet.ex
  test/swoosh/adapters/mailjet_test.exs
Labels: enhancement

#541 Fix gen_smtp check
  CHANGELOG.md
  lib/swoosh.ex
  lib/swoosh/adapters/smtp/helpers.ex
  mix.exs
Labels: bugfix

#542 Update helpers.ex
  CHANGELOG.md
  lib/swoosh.ex
  lib/swoosh/adapters/smtp/helpers.ex
  mix.exs
  mix.lock
Labels: skip-changelog

#543 add Recipient protocol
  lib/swoosh/email/recipient.ex
  mix.exs
  test/swoosh/email/recipient_test.exs
Labels: enhancement, minor

#545 integrate Recipient into Email
  lib/swoosh/email.ex
  test/swoosh/email/recipient_test.exs
Labels: enhancement
