Repository swoosh/swoosh, pull requests merged in 2023-06, with the labels that each got.

#773 Do not include Bcc header in delivered email
  lib/swoosh/adapters/smtp/helpers.ex
  test/swoosh/email/smtp_test.exs
Labels: bug

#776 Remove unnecessary sentence from README
  README.md
Labels: docs

#779 Fix BCC for adapters that depend on SMTP helper
  README.md
  lib/plug/mailbox_preview.ex
  lib/swoosh/adapters/amazon_ses.ex
  lib/swoosh/adapters/sendmail.ex
  lib/swoosh/adapters/smtp/helpers.ex
  mix.exs
  test/swoosh/adapters/amazonses_test.exs
  test/swoosh/adapters/mail_pace_test.exs
Labels: bugfix
